#!/usr/bin/env bash
set -euo pipefail

size="$(hyprctl getoption general:border_size -j | jq -r '.int')"
if [[ "$size" == "0" ]]; then
  hyprctl keyword general:border_size 2
else
  hyprctl keyword general:border_size 0
fi
