(custom-set-variables
 ;; Keep only the theme approvals generated by Customize.  Configuration
 ;; values belong in config.el so they do not silently override it later.
 '(custom-safe-themes
   '("ae20535e46a88faea5d65775ca5510c7385cbf334dfa7dde93c0cd22ed663ba"
     "a9028cd93db14a5d6cdadba789563cb90a97899c4da7df6f51d58bb390e54031"
     default)))
